language: cpp
sudo: false
compiler:
os:
  - linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - libgmp-dev
    - libmpfr-dev
    - binutils-dev
    - libboost-serialization1.55-dev
    - libboost-iostreams1.55-dev
    - g++-4.8

env: BUILD_TYPE="Debug" WITH_BFD="yes" WITH_PIRANHA="yes" INTEGER_CLASS="piranha"

install:
  - source bin/install_travis.sh
script:
  - bin/travis_clang.sh
  - bin/test_travis.sh
notifications:
  email: false
