language: cpp
sudo: false
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
dist: trusty
osx_image: xcode7.3
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - binutils-dev
    - g++-4.7

env:
  global:
    - secure: "Xj8vvg++O4mhcUTQGtHqXHhn8o5LklI/GkGWO6fcRXlJQszvpSMQiYfJ1UAYlmmuvXRNjWWdhEr7inJdHe1ZtNSXVU/jEICUytFBG6T3uuhOsBPkjVTp2en5vwsSPohaHcAnhoDyK9L48SBcTKLTCkTMhOitj9jk2renem0dX84="

  ## All these variables are sent into the bin/test_travis.sh script. See this
  ## script to know how they are used. Most of them are just passed to cmake,
  ## so if they are not set, cmake will use a default value. For the rest, the
  ## bin/test_travis.sh script usually checks for either "yes" or "no" in an if
  ## statement, so if the variable is not set, the other if branch will get
  ## executed.
  matrix:
  # Debug build (with BFD and INTEGER_CLASS from boostmp)
  - BUILD_TYPE="Debug" WITH_BFD="yes" INTEGER_CLASS="boostmp"

matrix:
  exclude:
    - compiler: clang
    - os: osx
  include:
    - env: BUILD_TYPE="Debug" WITH_BFD="yes" WITH_LLVM="3.8" WITH_BENCHMARKS_NONIUS="yes"
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - clang
          - libstdc++-4.8-dev
          - libgmp-dev
          - binutils-dev

before_install:
- |
   if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
     command curl -sSL https://rvm.io/mpapis.asc | gpg --import -;
     rvm get head || true
   fi
install:
  - source bin/install_travis.sh
script:
  - bin/test_travis.sh
  - bin/trigger_feedstock.sh
notifications:
  email: false

deploy:
  provider: pages
  skip_cleanup: true
  repo: symengine/symengine.github.io
  target_branch: master
  local_dir: doc/html
  github_token:
    secure: "nA/geBch3kWX4aURwe52JZNEG/JDR4RRkMvWqoqKTbnma54ohOokwaBlwmSc7lcmiq6YP8nI7uSCtK7EtqatJZewxNTNP8JXcuPb1IRuCXIvusakmk4iEqveEun5Igfge/6e6K/ujUiZchDT9ucEkxGNIAYDwrW0MPQ3ZG0Tla0="
  on:
    branch: master
    repo: symengine/symengine
    condition: $BUILD_DOXYGEN = yes
