language: cpp
sudo: false
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
    - binutils-dev
    - g++-4.7
    - gcc-5
    - g++-5

matrix:
  exclude:
    - os: linux
  include:
    - env: BUILD_TYPE="Debug" WITH_BFD="yes"
      compiler: clang
      os: osx
    - env: BUILD_TYPE="Release" WITH_BFD="yes"
      compiler: clang
      os: osx
    - env: BUILD_TYPE="Debug" WITH_BFD="yes"
      compiler: gcc
      os: osx
    - env: BUILD_TYPE="Release"  WITH_BFD="yes"
      compiler: gcc
      os: osx

install:
  - source bin/install_travis.sh
script:
  - bin/test_travis.sh
notifications:
  email: false
