language: cpp
sudo: false
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
    - binutils-dev
    - g++-4.7
    - gcc-5
    - g++-5
    - clang-format-3.7

matrix:
  exclude:
    - compiler: clang
    - os: osx
  include:
    - env: BUILD_TYPE="Debug" WITH_BFD="yes" WITH_PIRANHA="yes" INTEGER_CLASS="piranha"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - boost-latest
          packages:
          - libgmp-dev
          - libmpfr-dev
          - binutils-dev
          - libboost-serialization1.55-dev
          - libboost-iostreams1.55-dev
          - g++-4.8

install:
  - source bin/install_travis.sh
script:
  - bin/travis_clang.sh
  - bin/test_travis.sh
notifications:
  email: false
