version: '{build}'

#os: Visual Studio 2015 RC

environment:
  global:
    PLATFORMTOOLSET: "v140"
    PLATFORM: "Win32"

install:
- appveyor DownloadFile http://mpir.org/mpir-2.7.0.zip
- 7z x mpir-2.7.0.zip > NUL
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- msbuild mpir-2.7.0/build.vc14/lib_mpir_gc/lib_mpir_gc.vcxproj /p:Configuration=Debug /p:Platform=%PLATFORM% /p:PlatformToolset=%PLATFORMTOOLSET% /verbosity:normal
- msbuild mpir-2.7.0/build.vc14/lib_mpir_cxx/lib_mpir_cxx.vcxproj /p:Configuration=Debug /p:Platform=%PLATFORM% /p:PlatformToolset=%PLATFORMTOOLSET% /verbosity:normal
- copy mpir-2.7.0\build.vc14\lib_mpir_gc\%PLATFORM%\Debug\mpir.lib mpir-2.7.0\build.vc14\lib_mpir_gc\%PLATFORM%\Debug\gmp.lib
- copy mpir-2.7.0\build.vc14\lib_mpir_cxx\%PLATFORM%\Debug\mpirxx.lib mpir-2.7.0\build.vc14\lib_mpir_cxx\%PLATFORM%\Debug\gmpxx.lib

build_script:
- mkdir build
- cd build
- cmake -G "Visual Studio 14 2015" -DGMP_DIR=mpir-2.7.0/lib/%PLATFORM%/Debug;mpir-2.7.0/build.vc14/lib_mpir_gc/%PLATFORM%/Debug;mpir-2.7.0/build.vc14/lib_mpir_cxx/%PLATFORM%/Debug -DCMAKE_CXX_FLAGS_DEBUG="/D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 /W1" ..
# To build in Release mode:
#- cmake --build . --config Release
- cmake --build . --config Debug
- ctest

# Enable this to be able to login to the build worker
#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
