version: '{build}'

os: Visual Studio 2015 RC

environment:
  global:
    PLATFORMTOOLSET: "v90"
    PLATFORM: "Win32"

install:
- cinst cmake
- appveyor DownloadFile http://mpir.org/mpir-2.7.0.zip
- 7z x mpir-2.7.0.zip > NUL
- msbuild mpir-2.7.0/build.vc10/lib_mpir_gc/lib_mpir_gc.vcxproj /p:Configuration=Release /p:Platform=%PLATFORM% /p:PlatformToolset=%PLATFORMTOOLSET% /verbosity:normal
- msbuild mpir-2.7.0/build.vc10/lib_mpir_cxx/lib_mpir_cxx.vcxproj /p:Configuration=Release /p:Platform=%PLATFORM% /p:PlatformToolset=%PLATFORMTOOLSET% /verbosity:normal
- copy mpir-2.7.0\build.vc10\lib_mpir_gc\%PLATFORM%\Release\mpir.lib mpir-2.7.0\build.vc10\lib_mpir_gc\%PLATFORM%\Release\gmp.lib
- copy mpir-2.7.0\build.vc10\lib_mpir_cxx\%PLATFORM%\Release\mpirxx.lib mpir-2.7.0\build.vc10\lib_mpir_cxx\%PLATFORM%\Release\gmpxx.lib

build_script:
- mkdir build
- cd build
- cmake -G "Visual Studio 14 2015" -DGMP_DIR=mpir-2.7.0/lib/%PLATFORM%/Release;mpir-2.7.0/build.vc10/lib_mpir_gc/%PLATFORM%/Release;mpir-2.7.0/build.vc10/lib_mpir_cxx/%PLATFORM%/Release ..
- cmake --build .
- ctest

# Enable this to be able to login to the build worker
#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
