name: symengine
channels:
  - QuantStack
  - conda-forge
dependencies:
  - xeus-cling=0.4.7
  - gmp
  - mpfr
  - mpc
  - cmake
  - arb
  - llvmdev
  - notebook
  - gcc_linux-64  # [linux64]
  - gxx_linux-64  # [linux64]
